app/models/book.py
import datetime 

class Book:
    def __init__(self, title, author, pages, publish_date, description, isbn):
        self.title = title,
        self.author = author,
        self.pages = pages,
        self.publish_date = publish_date,
        self.description = description,
        self.isbn = isbn
    
        def to_json(self):
            return {
                "title": self.title,
                "autor": self.author,
                "pages": self.pages,
                "publish_date": datetime.datetime.strptime(str(self.publish_date), "%Y-%m-%d"),
                "description": self.description,
                "isbn": self.isbn
            }

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, DateField, IntegerField
from wtforms.validators import DataRequired

class BookForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    author = StringField("Author", validators=[DataRequired()])
    pages = IntegerField("Page numbers", validators=[DataRequired()])
    publish_date = DateField("Publish date", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    isbn = StringField("ISBN", validators=[DataRequired()])
    submit = SubmitField("Create book")

app/__init__.py
from flask import Flask
#from flask_bootstrap import Bootstrap

from .config import Config
from .routes.book import book_router
from .routes.personajes import ram_router

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    #Bootstrap(app)
    app.register_blueprint(ram_router)
    app.register_blueprint(book_router)
    return app

app/routes/book.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.forms import BookForm
from app.models.book import Book
from app.db import db


book_router = Blueprint("book_router", __name__)


@book_router.route("/crear", methods=['GET','POST'])
def create():
    book_form = BookForm()

    if book_form.validate_on_submit():
        new_book = Book(
        book_form.title.data,
        book_form.author.data,
        book_form.pages.data,
        book_form.publish_date.data,
        book_form.description.data,
        book_form.isbn.data
        )

        #insertar en la collection books
        db.books.insert_one(new_book.to_json())
        flash("Book created successfully","success")
        return redirect(url_for('book_router.index'))
    return render_template("create.html", book_form=book_form)

app/routes/personajes.py
import requests
from flask import Blueprint, render_template, flash, redirect, url_for
from app.db import db


ram_router = Blueprint("ram_router", __name__)

@ram_router.route("/")
@ram_router.route("/personajes")
def lista():
    personajes = db.personaje.find()
    return render_template("lista.html", personajes = personajes)

@ram_router.route("/personaje/<int:id>")
def detalles(id):
    personaje = db.personaje.find_one({"id":id})
    return render_template("personaje.html", personaje = personaje)

@ram_router.route("/capitulos")
def capitulos():
    capitulos = db.capitulos.find()
    return render_template("capitulos.html", capitulos = capitulos)

@ram_router.route("/capitulo/<int:id>")
def capitulo_detalles(id):
    capitulo = db.capitulos.find_one({"id":id})
    personajes_cap = db.personaje.find({"episodes":str(id)},{"name":1,"image":1,"type":1,"location":1})
    # db.personaje.find({"episodes":{$all:[str(id)]}})
    # db.personaje.find( { "episodes": { $all: [ [ str(id) ] ] } },{"name":1,"image":1} )

    return render_template("capitulo.html", capitulo = capitulo, personajes_cap = personajes_cap)


@ram_router.route("/import_db", methods=['GET','POST'])
def import_db():
    for id in range(1,100):
        url = requests.get('https://rickandmortyapi.com/api/character/'+str(id))
        url_json = url.json()
        episodes=[]
        for item in url_json['episode']:
            flag = item.split('/')
            episodes.append(flag[-1])

        data = {
            'id': url_json['id'],
            'name': url_json['name'],
            'status': url_json['status'],
            'species': url_json['species'],
            'type': url_json['type'],
            'gender': url_json['gender'],
            'origin': url_json['origin'],
            'location': url_json['location'],
            'image': url_json['image'],
            'episodes':episodes
        }
        db.personaje.insert_one(data)

    return redirect('/personajes')

@ram_router.route("/import_caps", methods=['GET','POST'])
def import_caps():
    for id in range(1,20):
        url = requests.get('https://rickandmortyapi.com/api/episode/'+str(id))
        url_json = url.json()

        data = {
            'id': url_json['id'],
            'name': url_json['name'],
            'air_date': url_json['air_date'],
            'episode': url_json['episode'],
            'characters': url_json['characters']
        }
        db.capitulos.insert_one(data)

    return redirect('/capitulos')

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/base_old.html
{#{% extends "bootstrap/base.html" %}#}

{% block body %}
<div class="container">
    {% for message in get_flashed_messages(category_filter=['success']) %}
    <div class="alert alert-success alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    
    {% for message in get_flashed_messages(category_filter=['error']) %}
    <div class="alert alert-danger alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    
    {% block content %} {% endblock %}
</div>
    {#% block scripts %} {{ super() }} {% endblock %#}
{% endblock %}

app/templates/capitulo.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <a href="{{ url_for ('ram_router.capitulos')}}">Capitulos</a>
    <h1 class="text-center"> Capitulo numero: {{ capitulo.id}}</h1>
    <div class="row row-cols-1 g-4">
        <div class="col d-flex justify-content-center">
            <div class="card " style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-8">
                        <div class="card-body bg-light">
                            <h5 class="card-subtitle mb-0"><small class="text-muted">Capitulo:</small></h5>
                            <h3 class="card-title mb-0">{{ capitulo.name }}</h3>
                            <p class="card-subtitle mb-0"><small class="text-muted">Fecha de estreno:</small></p>
                            <p class="card-subtitle mb-3">{{ capitulo.air_date }}</p>
                            <p class="card-subtitle mb-0"><small class="text-muted">Episodio:</small></p>
                            <p class="card-subtitle mb-0">{{ capitulo.episode }}</p>
                        </div>
                    </div>
                    <div class="col-md-4 my-auto d-block">
                        <img src="https://www.formulatv.com/images/series/posters/1500/1524/dest_2.jpg" width="180" height="200" class="rounded-start" alt="...">
                    </div>
                </div>
            </div>
        </div>
        <h4 class="text-center"> Personajes que aparecen en el episodio</h4>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for personaje_cap in personajes_cap %}
            <div class="col">
                <div class="card h-100">
                    <img src="{{personaje_cap['image'] }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{personaje_cap["name"] }}</h5>
                        <p>Type: {{ personaje_cap["type"]}}</p>
                        <p>Dimension: {{ personaje_cap["location"]["name"]}}</p>
                    </div>
                </div>
            </div>

            {% endfor %}
            <!-- {% for character in capitulo.characters %}
        {% set flag = character.split("/") %}
            <div class="col">
              <div class="card h-100">
                <img src="https://rickandmortyapi.com/api/character/avatar/{{flag[-1]}}.jpeg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                </div>
              </div>
            </div>
        {% endfor %} -->

        </div>


    </div>

</div>
</div>
{% endblock content %}

app/templates/capitulos.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <a href="{{ url_for ('ram_router.lista')}}">Personajes</a>
    <h1 class="text-center"> Capitulos de Rick and Morty</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">

        {% for capitulo in capitulos %}
        <a href="{{ url_for('ram_router.capitulo_detalles', id=capitulo.id)}}" style="text-decoration:none; color: #212529;">
            <div class="col">
                <div class="card " style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body bg-light">
                                <h5 class="card-subtitle mb-0"><small class="text-muted">Capitulo:</small></h5>
                                <h3 class="card-title mb-0">{{ capitulo.name }}</h3>
                                
                                <p class="card-subtitle mb-0"><small class="text-muted">Fecha de estreno:</small></p>
                                <p class="card-subtitle mb-3">{{ capitulo.air_date }}</p>
                                <p class="card-subtitle mb-0"><small class="text-muted">Episodio:</small></p>
                                <p class="card-subtitle mb-0">{{ capitulo.episode }}</p>

                            </div>
                        </div>
                        <div class="col-md-4 my-auto d-block">
                            <img src="https://www.formulatv.com/images/series/posters/1500/1524/dest_2.jpg" width="180" height="200" class="rounded-start" alt="...">
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}

    </div>
</div>
</div>
{% endblock content %}

app/templates/create.html
{% extends "base.html" %}

{% block content %}
  
  {#{% import "bootstrap/wtf.html" as wtf %}#}

  <h1>Create book</h1>

  {{ wtf.quick_form(book_form) }}

{% endblock content %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}

<a href="{{ url_for('book_router.create')}}">Crear libro</a>


<h1> Book lists</h1>
<div class="row" style="margin-top: 30px">
    {% for book in books %}
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <h5>{{ book.title }}</h5>
                <p>{{ book.author }}</p>
                <p># de paginas {{ book.pages }}</p>
                <p>{{ book.isbn }}</p>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock content %}

app/templates/lista.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <a href="{{ url_for ('ram_router.capitulos')}}">Capitulos</a>
    <h1 class="text-center"> Personajes Rick and Morty</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">

        {% for personaje in personajes %}
        <a href="{{ url_for('ram_router.detalles', id=personaje.id)}}" style="text-decoration:none; color: #212529;">
            <div class="col">
                <div class="card " style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ personaje.image }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body bg-light">
                                <h5 class="card-title mb-0">{{ personaje.name }}</h5>
                                <p class="card-subtitle mb-2">
                                    {% if personaje.status == 'Dead' %}
                                    <span
                                        class="position-absolute p-2 ml-0 mr-1 mt-1 bg-danger border border-light rounded-circle"></span>
                                    {% elif personaje.status == 'Alive' %}
                                    <span
                                        class="position-absolute p-2 ml-0 mr-1 mt-1 bg-success border border-light rounded-circle"></span>
                                    {% elif personaje.status == 'unknown' %}
                                    <span
                                        class="position-absolute p-2 ml-0 mr-1 mt-1 bg-warning border border-light rounded-circle"></span>
                                    {% endif %}
                                    <small class="text-muted mx-4"><span>{{ personaje.status }} - {{ personaje.species
                                            }}</span></small>
                                </p>
                                <p class="card-subtitle mb-0"><small class="text-muted">Last known location:</small></p>
                                <p class="card-subtitle mb-3">{{ personaje.location.name }}</p>
                                <p class="card-subtitle mb-0"><small class="text-muted">First seem in:</small></p>
                                <p class="card-subtitle mb-0">{{ personaje.origin.name }}</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}

    </div>
</div>
</div>
{% endblock content %}

app/templates/personaje.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <a href="{{ url_for ('ram_router.lista')}}">Home</a>
    
    <div class="row row-cols-1 g-4">
        <a href="{{ url_for('ram_router.detalles', id=personaje.id)}}" style="text-decoration:none; color: #212529;">
            <div class="col d-flex justify-content-center">
                <div class="card" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4 my-auto d-block">
                            <img src="{{ personaje.image }}" class="img-fluid rounded-circle" alt="...">
                            <h5 class="card-title mb-0 text-center">{{ personaje.name }}</h5>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body bg-light">
                                <h5 class="card-title mb-0">Detalles:</h5>
                                <p class="card-subtitle mb-2">
                                    {% if personaje.status == 'Dead' %}
                                    <span
                                        class="position-absolute p-2 ml-0 mr-1 mt-1 bg-danger border border-light rounded-circle"></span>
                                    {% elif personaje.status == 'Alive' %}
                                    <span
                                        class="position-absolute p-2 ml-0 mr-1 mt-1 bg-success border border-light rounded-circle"></span>
                                    {% elif personaje.status == 'unknown' %}
                                    <span
                                        class="position-absolute p-2 ml-0 mr-1 mt-1 bg-warning border border-light rounded-circle"></span>
                                    {% endif %}
                                    <small class="text-muted mx-4"><span>{{ personaje.status }} - {{ personaje.species
                                            }}</span></small>
                                </p>
                                
                                <p class="card-subtitle mb-2"><small class="text-muted">Type:</small> {{personaje.type}}</p>
                                <p class="card-subtitle mb-2"><small class="text-muted">Gender: </small>{{personaje.gender}}</p>
                                <p class="card-subtitle mb-0"><small class="text-muted">Last known location:</small></p>
                                <p class="card-subtitle mb-3">{{ personaje.location.name }}</p>
                                <p class="card-subtitle mb-0"><small class="text-muted">First seem in:</small></p>
                                <p class="card-subtitle mb-0">{{ personaje.origin.name }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>
</div>

{% endblock content %}